// Generated by CoffeeScript 1.7.1
(function() {
  define(['plugins/router'], function(router) {
    return {
      router: router,
      activate: function() {
        return router.map([
          {
            route: '',
            moduleId: 'viewmodels/projects',
            nav: true
          }, {
            route: 'project/:id',
            moduleId: 'viewmodels/tasks',
            nav: true
          }
        ]).buildNavigationModel().mapUnknownRoutes('viewmodels/error', 'not-found').activate();
      }
    };
  });

}).call(this);
